#-------------------------------
# General Site Settings

title: Gala Camacho Ferrari's website
logo: pipedream_b_small.png

menu:
- {name: Home, link: '/'}
- {name: About, link: '/about.html'}
# - {name: Thoughts, link: '/thoughts.html'}
- {name: Contact, link: '/contact.html'}
- {name: Experience, link: '/experience.html'}
# - {name: Life, link: '/life.html'}


# Hero Section

hero:
  hero-title: Gala <br>Camacho Ferrari

social:
- {icon: "ti-email", link: "mailto:gala.camacho+website@gmail.com"}
- {icon: "ti-linkedin", link: "https://www.linkedin.com/in/galacamacho/"}

#-------------------------------
# About (Section and Page)

# About Section
blurb:
  ¡Hola! 
  Welcome to my website. 

blurb-btn-link: '/about.html'
blurb-btn-name: More about me over here.


# About Page

# Work Process Section
# work-process:
#   - title : "Research and Plan"
#     icon : "assets/images/icons/plan.png"
#     content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
#   - title : "Design and Develop"
#     icon : "assets/images/icons/design.png"
#     content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
#   - title : "Deliver"
#     icon : "assets/images/icons/print.png"
#     content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."

# My Team Section
# team:
#   - title : "Women in STEMM Australia"
#     image : "assets/images/team/member-1.png"
#     designation : "Project Manager"

#-------------------------------
# Skills Section

# skills-title: Skills
# skills:
# - {name: Analytics, color: '#56B386', value: '80%'}
# - {name: Strategy, color: '#3A7CA5', value: '80%'}
# - {name: Communication, color: '#8C035E', value: '80%'}
# - {name: Collaboration, color: '#F7B53B', value: '80%'}


#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
- {name: Data Scientist, icon: 'icon-1.png', date: 'Dec 2021 - Present', organization: 'Diagonal Works'}

# Speaking Section
speaking-title: Past talks / panels / etc
speaking:
- {title: 'Large-area analytics for inclusive urbanism', name: 'GeoCom 2025' , organiser: 'AGI' , where: 'Edinburgh (UK)', date: '2025-02-27', image: 'agi.png', recording: ''}
- {title: 'Keynote: The Entreprenurial Spirit', organiser: 'The Data Lab Academy' , where: 'Edinbugh (UK)', date: '2024-10-10', image: 'tdl.png', recording: ''}
- {title: '20 Minute Neighbourhoods for Everyone', name: 'Geospatial Insights 2024: Innovations & Applications Across Sectors' , organiser: 'Location Data Scotland and AGI' , where: 'Edinburgh (UK)', date: '2024-08-27', image: 'lds_agi.png'}
- {title: 'Founders Panel ', organiser: 'Geovation Scotland' , where: 'Edinburgh (UK)', date: '2024-08-21', image: 'geovation.png'} 
- {title: 'Panel on Geospatial Data', name: 'Data & AI Meetup' , organiser: 'The Data Lab' , where: 'Edinburgh (UK)', date: '2024-08-07', image: 'tdl_data_ai.png'}
- {title: 'Routing algorithms, 20-minute neighbourhoods and hills in Scottish towns, speaker', name: 'TICTec - The Impacts of Civic Technology', organiser: 'MySociety', where: 'London (UK)', date: '2024-06-13', image: 'TICTeC.png', recording: 'https://www.youtube.com/watch?v=_VU8vCcLlps'}
- {title: 'Episode 236, speaker', name: 'Geomob Podcast', where: 'Remote (UK)', date: '2024-06-02', image: 'geomob.png', recording: 'https://thegeomob.com/podcast/episode-236'}
- {title: 'Inagural event, organiser', name: 'Geomob Edinburgh', where: 'Edinburgh (UK)', date: '2024-03-26', image: 'geomob.png'}
- {title: 'Open tools and alternative business models, speaker', name: 'People in Place Session' , organiser: 'SURF - Scotland''s regeneration forum' , where: 'Online (UK)', date: '2024-01-25', image: 'surf.png',}
- {title: 'Fireside chat with Elizabeth Pirrie, speaker', name: 'AccelerateHER + Techscaler Meetup: Edinburgh and Lothians' , organiser: 'AccelerateHER + Techscaler' , where: 'Edinburgh (UK)', date: '2023-11-02', image: 'accelerateher_techscaler.png',}
- {title: 'Using Tech for Positive Impact, speaker', name: 'Scotland’s Towns Partnership Learning Event: Digital – harnessing technology to empower people and places' , organiser: 'Scotland''s Towns Partnership' , where: 'Online (UK)', date: '2023-10-26', image: 'stp.png',}
- {title: 'What we don''t talk about when we talk about data, speaker', name: 'Monthly meetup' , organiser: 'Edinburgh Tech Meetup' , where: 'Edinburgh (UK)', date: '2022-10-11', image: 'edi_tech_meetup.png'}
- {title: 'None: a story of data that isn''t there, speaker', name: 'State of the Map - Firenze' , organiser: 'OpenStreetMap Foundation' , where: 'Firenze (Italy)', date: '2022-08-19', image: 'state_of_the_map.png', recording: 'https://www.youtube.com/watch?v=SWcojS_SrNc&list=PLQNy8KsDknCo4Hpk5_trylRC8FD2ge9ns&index=24'}
- {title: 'Better use of open data in the built environment?, co-speaker', name: 'ODI Fridays' , organiser: 'Open Data Institute' , where: 'Online (UK)', date: '2022-03-04', image: 'odi.png', recording: 'https://www.youtube.com/watch?v=ypkhvGyh58k'}
- {title: 'Creating space for everyone, speaker', name: 'Space and Geospatial Virtual Pavilion for COP26' , organiser: 'KTN' , where: 'Online (UK)', date: '2021-11-02', image: 'ktn_space.png', recording: 'https://www.youtube.com/watch?v=A14W_hLJ4Lk&list=PL-hp8OOckWOAYPIBCNdhjPCwAvYh-sO0A&index=3'}
- {title: 'Women''s Leadership in Geospatial, panel moderator', name: 'IWD' , organiser: 'Women+ in Geospatial' , where: 'Online (UK)', date: '2021-03-08', image: 'womeningeo_small.png', recording: 'https://youtu.be/ikcaeMwxvPo?t=1872'}
- {title: 'Melbourne tech scene exit interview, speaker', name: 'Byte into IT' , organiser: 'RRR' , where: 'Radio (Melbourne)', date: '2020-10-21', image: 'byte_into_it.png', recording: 'https://www.rrr.org.au/explore/podcasts/byte-into-it/episodes/4735-get-online-week-exit-interviews'}
- {title: 'Panel on a sustainable future with location intelligence, speaker', name:  'The Power of Place', organiser: 'Knowledge Transfer Network', where: 'Online (UK)', date: '2020-09-08', image: 'the_power_of_place.png', recording: 'https://ktn-uk.org/events/thepowerofplace-webinar-series-a-sustainable-future-with-location-intelligence/'}
- {title: 'Geospatial data is :exploading_head:, speaker', name: 'PyConline AU', organiser: 'PyCon Australia', where: 'Online (Oceania)', date: '2020-09-04', image: 'pyconline_au_2020.png', recording: 'https://youtu.be/WdmcUl8klnc'}
- {title: 'Technology as a field is changing because we are uprooting the stereotype of who a technologist is, speaker', name: 'Top Tech Trends Debate', organiser: 'The Churchill Club', where: 'Online (Aus)', date: '2020-09-01', image: top_tech_trends.png}
- {title: 'Data Pannel, speaker', name: 'GradGirls', organiser: 'VicICTForWomen', where: 'Online (Aus)', date: '2020-08-20', image: 'grad_girls.png'}
- {title: 'Understanding "place" through social data, speaker', name: 'Symposium: making unstructured data usable', organiser: 'Data, Systems and Society Research Network (DSSRN)', where: 'Melbourne', date: '2019-11-28'}
- {title: 'Social data: invading privacy or creating better cities, speaker', name: 'CSVConf.v4' , organiser: 'CSVConf' , where: 'Portland', date: '2019-05-09', image: 'csvconf4.png', recording: 'https://youtu.be/g-9LQjQF1xU'}
- {title: 'Multiple informal talks, mostly on pandas and geospatial data', name: 'Monthly meetup' , organiser: 'PyLadies Melbourne' , where: 'Melbourne', date: '2016-2019', image: 'pyladies.png'}
- {title: 'My rebellion, speaker', name: 'Rebel' , organiser: 'Code Like a Girl' , where: 'Melbourne', date: '2018-04-19', image: 'code_like_a_girl.png'}
- {title: 'How I #PressForProgress, speaker', name: 'IWD meetup' , organiser: 'Junior Developer Meetup' , where: 'Melbourne', date: '2018-03-08', image: 'junior_developer_meetup.png'}
# - {title: '', name: '' , organiser: '' , where: '', date: '', image: 'tiles_2.png', recording: ''}




#-------------------------------
# Education Section

# education-title: Education
# education:
# - {name: Marters in UX Design, date: '2006', organization: 'Masassusets Institute of Technology'}
# - {name: Honours in Fine Arts, date: '2004', organization: 'Harvard University'}
# - {name: Higher Secondary Certificat, date: '2000', organization: 'Cardiff School'}
# - {name: Secondary School Certificate, date: '1998', organization: 'Cardiff School'}


#-------------------------------
# Services Section

# services-title: Services
# services:
# - {
#     name: UI Design,
#     icon: ti-palette,
#     description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
#     active: # Add true to select section
#   }
# - {
#     name: UX Design,
#     icon: ti-vector,
#     description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
#     active: true # Add true to select section
#   }
# - {
#     name: Interaction Design,
#     icon: ti-panel,
#     description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
#     active: # Add true to select section
#   }



#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
# portfolio-home-items:
#   - image : "assets/images/portfolio/item-1.png"
#     url: "#"
    
#   - image : "assets/images/portfolio/item-2.png"
#     url: "#"
    
#   - image : "assets/images/portfolio/item-3.png"
#     url: "#"
    
#   - image : "assets/images/portfolio/item-4.png"
#     url: "#"
    
#   - image : "assets/images/portfolio/item-5.png"
#     url: "#"


# Portfolio Page
# portfolio-label:
# - {
#     title : "UI/UX Design",
#     type : "design"
#   }
# - {
#     title : "BRANDING",
#     type : "branding"
#   }
# - {
#     title : "ILLUSTRATION",
#     type : "illustration"
#   }

# portfolio-items:
#   - image : "assets/images/portfolio/item-1.png"
#     url: "#"
#     portfolio-type:
#      - type: "design"
#      - type: "illustration"
      
#   - image : "assets/images/portfolio/item-2.png"
#     url: "#"
#     portfolio-type:
#       - type: "branding"
      
#   - image : "assets/images/portfolio/item-3.png"
#     url: "#"
#     portfolio-type:
#       - type: "illustration"
      
#   - image : "assets/images/portfolio/item-6.png"
#     url: "#"
#     portfolio-type:
#       - type: "design"
#       - type: "branding"
      
#   - image : "assets/images/portfolio/item-8.png"
#     url: "#"
#     portfolio-type:
#       - type: "illustration"
      
#   - image : "assets/images/portfolio/item-5.png"
#     url: "#"
#     portfolio-type:
#       - type: "design"
      
#   - image : "assets/images/portfolio/item-1.png"
#     url: "#"
#     portfolio-type:
#       - type: "branding"
      
#   - image : "assets/images/portfolio/item-3.png"
#     url: "#"
#     portfolio-type:
#       - type: "design"
#       - type: "illustration"
#       - type: "branding"
      
#   - image : "assets/images/portfolio/item-7.png"
#     url: "#"
#     portfolio-type:
#       - type: "illustration"


#-------------------------------
# Testimonials Section

# testimonial-items:
#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation : "CEO, Funder"
#     content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    
#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    
#   - name: "Jesica Gomez"
#     image: "assets/images/testimonial/client-1.png"
#     designation: "CEO, Funder"
#     content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."


#-------------------------------
# Client Slider Section

# client-slider-items:
#   - logo: "assets/images/clients-logo/client-logo-1.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-2.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-3.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-4.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-5.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-1.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-2.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-3.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-4.png"
#     url: "#"
    
#   - logo: "assets/images/clients-logo/client-logo-5.png"
#     url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: gala.camacho+website@gmail.com